organizers:
  - venue: Workshop <a href="https://sites.google.com/view/newmodality-aidrug/home">AI for New Drug Modalities</a> at <b>NeurIPS</b> 2024

reviewers:
  - venue: "Conference on Neural Information Processing Systems (<b>NeurIPS</b>)"
    year: "2023 - 2024"

  - venue: "Conference on Neural Information Processing Systems (<b>NeurIPS</b>) Datasets and Benchmarks track"
    year: "2022 - 2024"

  - venue: "International Conference on Machine Learning (<b>ICML</b>)"
    year: "2023 - 2024"

  - venue: "International Conference on Learning Representation (<b>ICLR</b>)"
    year: "2024"

  - venue: "AAAI Conference on Artificial Intelligence (<b>AAAI</b>)"
    year: "2024"

  - venue: "International Conference on Information and Knowledge Management (<b>CIKM</b>)"
    year: "2023 - 2024"

  - venue: "IEEE International Conference on Big Data (<b>IEEE BigData</b>)"
    year: "2024"

  - venue: "IEEE Transactions on Pattern Analysis and Machine Intelligence (<b>TPAMI</b>)"





   
   
